version: "3"
services:
  # private subnet
  soa:
    build: 
      context: ./Intranet/soa
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 192.168.1.2
    container_name: soa

  resolver:
    build: 
      context: ./Intranet/resolver
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 192.168.1.3
    container_name: resolver
    

  mail:
    dns: 192.168.1.3
    build:
      context: ./Intranet/mail
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 192.168.1.4
    container_name: mail

  web_erp: 
    dns: 192.168.1.3
    build: 
      context: ./Intranet/web
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 192.168.1.5
    container_name: erp

  web_public:
    dns: 192.168.1.3
    build:
      context: ./Public/web_public
      dockerfile: Dockerfile
    ports:
      - 80:80/tcp
    networks:
      intranet:
        ipv4_address: 192.168.1.6
    container_name: web_public
    
  client:
    dns: 192.168.1.3
    build: 
      context: ./Intranet/client
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 192.168.1.7
    container_name: client

  client2:
    dns: 192.168.1.3
    build: 
      context: ./Intranet/client2
      dockerfile: Dockerfile
    networks:
      intranet:
        ipv4_address: 192.168.1.8
    container_name: client2

  # public services
  external_soa:
    build: 
      context: ./Public/soa
      dockerfile: Dockerfile
    ports:
      - "165.22.67.79:53:53/udp"
      - "165.22.67.79:53:53/tcp"
    container_name: external_soa

  external_mail:
    build:
      context: ./Public/mail
      dockerfile: Dockerfile
    ports:
      - 25:25/tcp
      - 465:465/tcp
      - 587:587/tcp
      - 993:993/tcp
      - 995:995/tcp
    container_name: external_mail

networks:
  intranet:
    name: intranet
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
